---
title: "correlation_featImport_IndicatorValue"
author: "Estephe Kana, Eugeni Belda & Edi Prifti"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

<!-- This report presents the comparative analysis between an **Indval** and **Predomics**. **Indval** method is used by ecologist to determine the occurrence or abundance of a small set of indicator species, as an alternative to sampling the entire community. In the machine learning package **Predomics**, we will use the algorithm **Terbeam** with languages **terinter** and **bininter** to perform the same analysis and compare their results. For these analysis, we will use the dataset from Baletaud et al. on «Baited video reveal fish diversity in the vast inter‑reef habitats of a marine tropical lagoon» that contains 148 species from two sets of habitat: Inshore (Bay + Lagoon) and Offshore (Barrier zone). -->

### Loading packages
Here we are loading the necessary packages for the analysis
```{r load the packages, message=FALSE, warning=FALSE}
library(readr) # for data import
library(momr) # for normalizing, visualizing and microbiome analyses
library(ggplot2) # for plots
library(gridExtra) # for multiple plots
library(vegan) # for ecological analyses
library(viridis) # for colour maps
library(stats) # for euclidean distance computation
library(predomics) # loading predomics
library(patchwork) # to display multiples graphs in the same figure
library(dplyr)
library(reshape2)
library(plyr)
library(ggrepel)
library(ggVennDiagram)
library(ggpubr)
library(ggrepel)
library(labdsv) # for Indicator Species Analysis
```

# define dataframe

```{r plotting venndiagram, message=FALSE,results='hide', warning=FALSE, fig.height = 6, fig.width = 10, warning=FALSE}
df1 <- as.data.frame(read_csv("/data/projects/aime/analyses/metabarcoding/4.data_video_analysis/InValSpecies_video_data.csv", show_col_types = FALSE))

# View(df1)

df2 <- as.data.frame(read_csv("/data/projects/aime/analyses/metabarcoding/4.data_video_analysis/indicSpeciesPredomics/terBeam_terinter/IndicSpeciesPredomics_terBeam_terinter.csv", show_col_types = FALSE))

# View(df2)

df3 <- as.data.frame(read_csv("/data/projects/aime/analyses/metabarcoding/4.data_video_analysis/indicSpeciesPredomics/terBeam_bininter/IndicSpeciesPredomics_terBeam_bininter.csv", show_col_types = FALSE))

# View(df3)

# define combine table for Indval and predomics_terinter species

inval_terinter_species <- merge(df1, df2, by= "Species", all = TRUE)

# View(inval_terinter_species)

inval_predomics_species <- merge(inval_terinter_species, df3, by= "Species", all = TRUE)

# View(inval_predomics_species)

# View(inval_terinter_species)
indval_species = filter(inval_predomics_species, IsIndSpec == 1)
terinter_species = filter(inval_predomics_species, IsInFBM.x == 1)
bininter_species = filter(inval_predomics_species, IsInFBM.y == 1)

df1_pa <- as.data.frame(read_csv("/data/projects/aime/analyses/metabarcoding/4.data_video_analysis/InValSpecies_video_data_pres_abs.csv", show_col_types = FALSE))

# View(df1)

df2_pa <- as.data.frame(read_csv("/data/projects/aime/analyses/metabarcoding/4.data_video_analysis/indicSpeciesPredomics/terBeam_terinter/IndicSpecies_predomicsResults_Offshore_Inshore_pres_abs.csv", show_col_types = FALSE))

# View(df2)

df3_pa <- as.data.frame(read_csv("/data/projects/aime/analyses/metabarcoding/4.data_video_analysis/indicSpeciesPredomics/terBeam_bininter/IndicSpecies_predomicsResults_Offshore_Inshore_pres_abs.csv", show_col_types = FALSE))

# View(df3)

# define combine table for Indval and predomics_terinter species

inval_terinter_species_pa <- merge(df1_pa, df2_pa, by= "Species", all = TRUE)

# View(inval_terinter_species)

inval_predomics_species_pa <- merge(inval_terinter_species_pa, df3_pa, by= "Species", all = TRUE)

# View(inval_predomics_species)

# View(inval_terinter_species)
indval_species_pa = filter(inval_predomics_species_pa, IsIndSpec == 1)
terinter_species_pa = filter(inval_predomics_species_pa, IsInFBM.x == 1)
bininter_species_pa = filter(inval_predomics_species_pa, IsInFBM.y == 1)
```


## Analyze the correlation between indicator value and Feature importance based on abundance data

<!-- - In the first figure, we can see a positive and highly significant correlation between the indicator value and feature importance for core species of Indval and predomics algorithms. -->
<!-- - The core species **Nemipterus peronii** has the highest value of feature importance for bininter and a much lower value for the terinter model -->
<!-- - The second figure shows that the core species for Indval-terinter or indval-bininter are the most abundant than those for each model separately. -->

```{r Correlation ind_value and feat_import on abund, message=FALSE,results='hide', warning=FALSE, fig.height = 5, fig.width = 10}
# get indics_species from indval and terinter
indval_terinter_species= rbind(indval_species, terinter_species)

indval_terinter_species$color= ifelse(indval_terinter_species$IsIndSpec==1 & indval_terinter_species$IsInFBM.x==0,
                                      -1, 
                                      ifelse(indval_terinter_species$IsIndSpec==1 & indval_terinter_species$IsInFBM.x==1, 0, 1))
indval_terinter_species$color <- factor(indval_terinter_species$color, levels = c(-1,0,1))

# get indics_species from indval and bininter
indval_bininter_species= rbind(indval_species, bininter_species)
indval_bininter_species$color= ifelse(indval_bininter_species$IsIndSpec==1 & indval_bininter_species$IsInFBM.y==0,
                                      -1, 
                                      ifelse(indval_bininter_species$IsIndSpec==1 & indval_bininter_species$IsInFBM.y==1, 0, 1))
indval_bininter_species$color <- factor(indval_bininter_species$color, levels = c(-1,0,1))

# basic scatterplot
indval_terinter_species$color <- factor(indval_terinter_species$color, levels=c(-1,0,1), labels = c("indVal-only","indVal-Pred","Pred-only"))
indval_terinter_species$label <- ifelse(indval_terinter_species$Species %in% "Nemipterus peronii", as.character(indval_terinter_species$Species),NA)
match("Nemipterus peronii", indval_terinter_species$Species)
indval.feat1 = ggplot(unique(indval_terinter_species), aes(x=featImport.x, y=indicator_value)) + 
  geom_point(aes(color=color)) + 
  stat_cor(method = "spearman") + 
  geom_text_repel(aes(label=label)) +  xlim(0,40) + ylim(0,1)+
  # coord_cartesian(xlim = c(0, 35))+
  labs(x= "feature_importance", y= "indicator_value", title = "Indval vs terinter", color = "speciesPrev")+
  theme(legend.position = "right")

indval_bininter_species$color <- factor(indval_bininter_species$color, levels=c(-1,0,1), labels = c("indVal-only","indVal-Pred","Pred-only"))
indval_bininter_species$label <- ifelse(indval_bininter_species$featImport.y>30,as.character(indval_bininter_species$Species),NA)

indval.feat2 = ggplot(unique(indval_bininter_species), aes(x=featImport.y, y=indicator_value)) + 
  geom_point(aes(color=color)) +
  geom_text_repel(aes(label=label)) + 
  stat_cor(method = "spearman") +  xlim(0,40) + ylim(0,1)+
  # coord_cartesian(xlim = c(0, 35))+
  labs(x= "feature_importance", y= "indicator_value", title = "Indval vs bininter", color = "speciesPrev")+
  theme(legend.position = "none")

cor_scatt_abund <- ggarrange(indval.feat1,
                      indval.feat2, widths=c(2.6,2))
cor_scatt_abund

##boxplot bininter feat imp
df.1 <- unique(indval_bininter_species)
df.1.plot <- ggplot(df.1, aes(x=color, y=featImport.y)) + 
  geom_boxplot(outlier.shape = NA) +  
  geom_point(position = position_jitter(.05), alpha=.5) + 
  stat_compare_means(method = "wilcox", comparisons = combn(x = levels(df.1$color), m = 2, simplify = FALSE)) + 
  labs(x= "species_prev", y= "Feature importance") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

##boxplot bininter feat imp
df.2 <- unique(indval_terinter_species)
df.2.plot <- ggplot(df.2, aes(x=color, y=featImport.x)) + 
  geom_boxplot(outlier.shape = NA) +  
  geom_point(position = position_jitter(.05), alpha=.5) + 
  stat_compare_means(method = "wilcox", comparisons = combn(x = levels(df.2$color), m = 2, simplify = FALSE)) + 
  labs(x= "species_prev", y= "Feature importance") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

cor_box_abund <- grid.arrange(df.2.plot + ggtitle("terinter"), 
                    df.1.plot + ggtitle("bininter"), ncol=2)
cor_box_abund
```

## Analyze the correlation between indicator value and Feature importance based on presence/absence 

<!-- - In the first figure, we can see a positive and highly significant correlation between the indicator value and feature importance for core species of Indval and predomics algorithms. -->
<!-- - The core species **Nemipterus peronii** has the highest value of feature importance for bininter and a much lower value for the terinter model -->
<!-- - The second figure shows that the core species for Indval-terinter or indval-bininter are the most abundant than those for each model separately. -->

```{r Correlation ind_value and feat_import on pa, message=FALSE,results='hide', warning=FALSE, fig.height = 5, fig.width = 10}
# get indics_species from indval and terinter
indval_terinter_species_pa= rbind(indval_species_pa, terinter_species_pa)

indval_terinter_species_pa$color= ifelse(indval_terinter_species_pa$IsIndSpec==1 & indval_terinter_species_pa$IsInFBM.x==0,
                                      -1, 
                                      ifelse(indval_terinter_species_pa$IsIndSpec==1 & indval_terinter_species_pa$IsInFBM.x==1, 0, 1))
indval_terinter_species_pa$color <- factor(indval_terinter_species_pa$color, levels = c(-1,0,1))

# get indics_species from indval and bininter
indval_bininter_species_pa= rbind(indval_species_pa, bininter_species_pa)
indval_bininter_species_pa$color= ifelse(indval_bininter_species_pa$IsIndSpec==1 & indval_bininter_species_pa$IsInFBM.y==0,
                                      -1, 
                                      ifelse(indval_bininter_species_pa$IsIndSpec==1 & indval_bininter_species_pa$IsInFBM.y==1, 0, 1))
indval_bininter_species_pa$color <- factor(indval_bininter_species_pa$color, levels = c(-1,0,1))

# basic scatterplot
indval_terinter_species_pa$color <- factor(indval_terinter_species_pa$color, levels=c(-1,0,1), labels = c("indVal-only","indVal-Pred","Pred-only"))
indval_terinter_species_pa$label <- ifelse(indval_terinter_species_pa$Species %in% "Nemipterus peronii", as.character(indval_terinter_species_pa$Species),NA)
match("Nemipterus peronii", indval_terinter_species_pa$Species)
indval.feat1_pa = ggplot(unique(indval_terinter_species_pa), aes(x=featImport.x, y=indicator_value)) + 
  geom_point(aes(color=color)) + 
  stat_cor(method = "spearman") + 
  geom_text_repel(aes(label=label)) +  xlim(0,40) + ylim(0,1)+
  # coord_cartesian(xlim = c(0, 35))+
  labs(x= "feature_importance", y= "indicator_value", title = "Indval vs terinter", color = "speciesPrev")+
  theme(legend.position = "right")

indval_bininter_species_pa$color <- factor(indval_bininter_species_pa$color, levels=c(-1,0,1), labels = c("indVal-only","indVal-Pred","Pred-only"))
indval_bininter_species_pa$label <- ifelse(indval_bininter_species_pa$featImport.y>30,as.character(indval_bininter_species_pa$Species),NA)

indval.feat2_pa = ggplot(unique(indval_bininter_species_pa), aes(x=featImport.y, y=indicator_value)) + 
  geom_point(aes(color=color)) + scale_color_manual(values = c("#F8766D", "#00BA38"))+
  geom_text_repel(aes(label=label)) + 
  stat_cor(method = "spearman") + xlim(0,40) + ylim(0,1)+
  # coord_cartesian(xlim = c(0, 35))+ 
  labs(x= "feature_importance", y= "indicator_value", title = "Indval vs bininter", color = "speciesPrev")+
  theme(legend.position = "none")

cor_scatt_pa <- ggarrange(indval.feat1_pa,
                      indval.feat2_pa, widths=c(2.6,2))
cor_scatt_pa

##boxplot bininter feat imp
df.1_pa <- unique(indval_bininter_species_pa)
df.1_pa.plot <- ggplot(df.1_pa, aes(x=color, y=featImport.y)) + 
  geom_boxplot(outlier.shape = NA) +  
  geom_point(position = position_jitter(.05), alpha=.5) + 
  stat_compare_means(method = "wilcox", comparisons = combn(x = levels(df.1_pa$color), m = 2, simplify = FALSE)) + 
  labs(x= "species_prev", y= "Feature importance") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

##boxplot bininter feat imp
df.2_pa <- unique(indval_terinter_species_pa)
df.2_pa.plot <- ggplot(df.2_pa, aes(x=color, y=featImport.x)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitter(.05), alpha=.5) +
  stat_compare_means(method = "wilcox", comparisons = combn(x = levels(df.2_pa$color), m = 2, simplify = FALSE)) +
  labs(x= "species_prev", y= "Feature importance") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

cor_box_pa <- grid.arrange(df.2_pa.plot + ggtitle("terinter"), 
                      df.1_pa.plot + ggtitle("bininter"), ncol=2)

cor_box_pa
```